[package]
name = "cody-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
gix = "0.50.1"

tree-sitter.workspace = true

scip-syntax = { path = "../scip-syntax" }
scip-treesitter-languages = { path = "../scip-treesitter-languages" }
